apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadehub-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arcadehub-server
  template:
    metadata:
      labels:
        app: arcadehub-server
    spec:
      containers:
      - name: arcadehub
        image: arcadehub/server:1.5.0
        ports:
        - containerPort: 5050
        - containerPort: 8081
        env:
        - name: DB_URL
          value: "jdbc:postgresql://db:5432/arcadehub"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5